# CI test image for building the CLI
FROM node:lts-alpine as react-native-cli-feature-builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY babel.config.js lerna.json .eslintignore .eslintrc.js jest.config.js tsconfig.json packages/expo/unimodules-core.d.ts ./
COPY bin ./bin
COPY packages ./packages

RUN npm run bootstrap
